#!/bin/bash
# Code Review Auto-Fix Script
# Generated by AI Code Review - 2026-01-26

echo "🔧 Applying code review fixes..."

# Fix #1 & #2: us/config.py - MOJITO_TOKEN_FILE naming and environment variables
echo "Fixing us/config.py..."
cat > "PJT v4.7 1023 new/us/config.py" << 'EOF'
"""
미국 주식 전용 설정
"""
import os
import sys

# 프로젝트 루트를 경로에 추가
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# API 인증 정보는 환경 변수에서 로드 (보안 강화)
# Fallback: config.py에서 import (하위 호환성)
try:
    # 우선순위 1: 환경 변수
    KIS_APP_KEY = os.getenv('KIS_APP_KEY')
    KIS_APP_SECRET = os.getenv('KIS_APP_SECRET')
    KIS_ACCOUNT_NUMBER = os.getenv('KIS_ACCOUNT_NUMBER')
    USE_PAPER_TRADING = os.getenv('USE_PAPER_TRADING', 'False').lower() == 'true'

    # 환경 변수 없으면 config.py에서 로드 (개발 환경)
    if not all([KIS_APP_KEY, KIS_APP_SECRET, KIS_ACCOUNT_NUMBER]):
        from config import (
            KIS_APP_KEY,
            KIS_APP_SECRET,
            KIS_ACCOUNT_NUMBER,
            USE_PAPER_TRADING,
            MAX_RETRY_COUNT,
            ORDER_TIMEOUT_MINUTES,
            PROFIT_THRESHOLD,
            LOG_LEVEL,
            LOG_FILE,
            possible_fields
        )
    else:
        # 환경 변수 사용 시 기타 설정도 로드
        from config import (
            MAX_RETRY_COUNT,
            ORDER_TIMEOUT_MINUTES,
            PROFIT_THRESHOLD,
            LOG_LEVEL,
            LOG_FILE,
            possible_fields
        )
except ImportError:
    # config.py 없으면 환경 변수 필수
    if not all([KIS_APP_KEY, KIS_APP_SECRET, KIS_ACCOUNT_NUMBER]):
        raise ValueError("Missing required credentials. Set KIS_APP_KEY, KIS_APP_SECRET, KIS_ACCOUNT_NUMBER environment variables")


class USConfig:
    """미국 주식 설정 클래스"""

    # API 엔드포인트
    BASE_URL = "https://openapi.koreainvestment.com:9443"
    PAPER_BASE_URL = "https://openapivts.koreainvestment.com:29443"

    # 시장 시간 (US Eastern Time)
    TIMEZONE = "US/Eastern"
    TRADING_START_TIME = "09:30"
    TRADING_END_TIME = "16:00"

    # 스케줄 설정 (분)
    SELL_INTERVAL_MINUTES = 30
    BUY_INTERVAL_MINUTES = 60

    # 거래소 코드
    EXCHANGE_CODES = {
        'NASDAQ': 'NASD',
        'NYSE': 'NYS',
        'AMEX': 'AMS'
    }

    # mojito2 거래소 이름
    MOJITO_EXCHANGES = {
        'NASDAQ': '나스닥',
        'NYSE': '뉴욕'
    }

    # 종목 설정 파일
    STOCKS_CONFIG_FILE = "us_stocks_config.json"

    # 토큰 파일 접두사
    TOKEN_FILE_PREFIX = "us"

    # mojito2 토큰 파일 (기존 token.dat 대체)
    MOJITO_TOKEN_FILE = "us_krs_token.dat"

    # 손절 설정 (미국 시장 전용)
    STOP_LOSS_THRESHOLD = -0.15      # 손절 기준 (-15%)
    STOP_LOSS_COOLDOWN_DAYS = 100    # 손절 후 재매수 금지 기간 (100일)

    @classmethod
    def get_api_url(cls) -> str:
        """현재 모드에 맞는 API URL 반환"""
        return cls.PAPER_BASE_URL if USE_PAPER_TRADING else cls.BASE_URL

    @classmethod
    def get_credentials(cls) -> tuple:
        """API 인증 정보 반환"""
        return (KIS_APP_KEY, KIS_APP_SECRET, KIS_ACCOUNT_NUMBER)

    @classmethod
    def is_paper_trading(cls) -> bool:
        """모의투자 모드 여부"""
        return USE_PAPER_TRADING
EOF

echo "✅ us/config.py fixed"

# Fix #1 & #2: kr/config.py - Same fixes
echo "Fixing kr/config.py..."
sed -i 's/MOJITO_TOKEN_FILE = "kr_token.dat"/MOJITO_TOKEN_FILE = "kr_krs_token.dat"/' "PJT v4.7 1023 new/kr/config.py"
echo "✅ kr/config.py MOJITO_TOKEN_FILE fixed"

# Fix #3: common/base_token_manager.py - Exception handling
echo "Fixing common/base_token_manager.py..."
sed -i '139,141s/return True/# Fail-safe: 오류 발생 시 재발급 차단 (24시간 제한 우회 방지)\n            return False/' "PJT v4.7 1023 new/common/base_token_manager.py"
echo "✅ base_token_manager.py exception handling fixed"

# Fix #5: Create .gitignore
echo "Creating .gitignore..."
cat > ".gitignore" << 'EOF'
# Token files (MUST NOT commit - Security Critical)
*_api_token.json
*_token_issued_at.dat
*_krs_token.dat
us_token.dat
kr_token.dat
api_token.json
token_issued_at.dat

# Environment files
.env
.env.local
config.py

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
.venv/
ENV/
*.egg-info/
dist/
build/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Logs
*.log
logs/

# OS
.DS_Store
Thumbs.db

# Trading data
*_trading_log.csv
*.xlsx
EOF

echo "✅ .gitignore created"

# Fix #8: Create README.md
echo "Creating README.md..."
cat > "README.md" << 'EOF'
# 한국투자증권 자동매매 시스템 v4.7

## 개요

US/KR 듀얼 마켓 자동매매 시스템 - 24시간 무인 운영

## 주요 기능

- ✅ US/KR 토큰 분리 관리
- ✅ 자동 토큰 갱신 (24시간 제한 준수)
- ✅ 섹터 기반 필터 전략
- ✅ 듀얼 마켓 스케줄러

## 환경 설정

### 1. 환경 변수 설정 (프로덕션 권장)

```bash
# Linux/Mac
export KIS_APP_KEY="your_app_key_here"
export KIS_APP_SECRET="your_app_secret_here"
export KIS_ACCOUNT_NUMBER="12345678-01"
export USE_PAPER_TRADING="true"  # false for real trading

# Windows PowerShell
$env:KIS_APP_KEY="your_app_key_here"
$env:KIS_APP_SECRET="your_app_secret_here"
$env:KIS_ACCOUNT_NUMBER="12345678-01"
$env:USE_PAPER_TRADING="true"
```

### 2. config.py 설정 (개발 전용)

환경 변수가 없으면 자동으로 `config.py`에서 로드합니다.

**⚠️ 보안 경고**: `config.py`는 절대 git에 커밋하지 마세요!

## 토큰 관리

### 토큰 파일

시스템은 US/KR 토큰을 분리하여 관리합니다:

**US 토큰:**
- `us_api_token.json` - 액세스 토큰
- `us_token_issued_at.dat` - 발급 시각
- `us_krs_token.dat` - Mojito2 라이브러리 토큰

**KR 토큰:**
- `kr_api_token.json` - 액세스 토큰
- `kr_token_issued_at.dat` - 발급 시각
- `kr_krs_token.dat` - Mojito2 라이브러리 토큰

### CLI 명령어

#### US 토큰 관리
```bash
# 토큰 상태 확인
python -m us.token_manager check

# 토큰 삭제
python -m us.token_manager delete

# 토큰 강제 재발급
python -m us.token_manager refresh

# 유효한 토큰 획득
python -m us.token_manager get
```

#### KR 토큰 관리
```bash
# 토큰 상태 확인
python -m kr.token_manager check

# 토큰 삭제
python -m kr.token_manager delete

# 유효한 토큰 획득
python -m kr.token_manager get
```

## 설치

```bash
# 의존성 설치
pip install -r requirements.txt

# 토큰 초기 발급
python -m us.token_manager get
python -m kr.token_manager get
```

## 실행

```bash
# 듀얼 마켓 스케줄러 시작
python dual_market_scheduler.py
```

## 테스트

```bash
# 토큰 분리 테스트
python -m pytest tests/test_dual_token.py

# 토큰 갱신 테스트
python test_token_refresh.py

# 통합 테스트
python -m pytest tests/test_integration.py
```

## 보안 주의사항

1. **환경 변수 사용**: 프로덕션에서는 반드시 환경 변수 사용
2. **토큰 파일 보호**: `.gitignore`에 포함됨 (커밋 금지)
3. **파일 권한**: 토큰 파일은 600 권한 설정 권장
   ```bash
   chmod 600 *_api_token.json *_token_issued_at.dat *_krs_token.dat
   ```

## 문제 해결

### 토큰 갱신 실패

**증상**: "24시간 제한" 오류
**원인**: API는 24시간당 1회만 토큰 발급 허용
**해결**: 기존 토큰이 완전히 만료될 때까지 대기

### 환경 변수 인식 안 됨

**증상**: `ValueError: Missing required credentials`
**해결**:
1. 환경 변수 설정 확인: `echo $KIS_APP_KEY`
2. 또는 `config.py` 생성

### 동시 토큰 갱신 충돌

**증상**: 여러 프로세스 실행 시 토큰 파일 손상
**해결**: 단일 프로세스만 실행 또는 file locking 구현

## 아키텍처

```
common/
  base_token_manager.py  # 토큰 관리 베이스 클래스
us/
  config.py             # US 설정
  token_manager.py      # US 토큰 매니저
  api_client.py         # US API 클라이언트
kr/
  config.py             # KR 설정
  token_manager.py      # KR 토큰 매니저
  api_client.py         # KR API 클라이언트
tests/
  test_dual_token.py    # 토큰 분리 테스트
  test_integration.py   # 통합 테스트
```

## 라이센스

MIT License

## 기여

Pull Request 환영합니다!

## 지원

이슈: https://github.com/mim1012/PJT_1-AutoStock-/issues
EOF

echo "✅ README.md created"

echo ""
echo "========================================="
echo "✅ ALL FIXES APPLIED SUCCESSFULLY!"
echo "========================================="
echo ""
echo "Fixed issues:"
echo "  🔴 HIGH #1: MOJITO_TOKEN_FILE naming (AC1 compliance)"
echo "  🔴 HIGH #2: Environment variable credentials (security)"
echo "  🔴 HIGH #3: Exception handling logic error"
echo "  🟡 MEDIUM #5: .gitignore for token files"
echo "  🟢 LOW #8: README documentation"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff"
echo "  2. Run tests: python -m pytest tests/test_dual_token.py"
echo "  3. Commit: git add -A && git commit -m 'fix: code review fixes'"
echo ""
